language: python
dist: trusty
sudo: true
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy
env:
  - SQLALCHEMY_VERSION=">=1.0,<1.1"
  - SQLALCHEMY_VERSION=">=1.1,<1.2"
  - SQLALCHEMY_VERSION=">=1.2b1,<1.3"
before_install:
  - sudo sh -c "echo 'deb http://dev.monetdb.org/downloads/deb/ trusty monetdb' > /etc/apt/sources.list.d/monetdb.list"
  - wget --output-document=- http://dev.monetdb.org/downloads/MonetDB-GPG-KEY | sudo
    apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq monetdb5-sql monetdb-client
  - sudo usermod -a -G monetdb $USER
  - sudo sh -c "echo 'STARTUP=yes\nDBFARM=/var/lib/monetdb\n' > /etc/default/monetdb5-sql"
  - sudo service monetdb5-sql start
  - sudo monetdbd set control=yes /var/lib/monetdb
  - sudo monetdbd set passphrase=testdb /var/lib/monetdb
  - sudo monetdb create test
  - sudo monetdb release test
  - echo -e "user=monetdb\npassword=monetdb\n" > ~/.monetdb
  - echo "create schema test_schema;" | mclient -d test
  - echo "create schema test_schema2;" | mclient -d test
  - echo "alter user monetdb set schema test_schema2;" | mclient -d test
install:
  - pip install sqlalchemy${SQLALCHEMY_VERSION}
  - pip install -r test/requirements.txt
  - pip install -e .
script:
  - pytest
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: gH93ltiwnVy5MsZvW0AM6ZNYIc9VGU5Hw/UH3jb0Conz4Rgs5idb9zjPMUa93z/l7t6YjNgLEXt5BtAXkkphDCW0ugwxDH3JXwn096A+hPhu7yK1weUtS+XyHhVGdyZijclIS9AmqxFYSWav681I5J0P3P80F+yu4VgE1nYnILA=
  on:
    tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/352a01a6eaa4e05408fd
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
