name: Linux

on: [push]

jobs:
  linux-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        branch: [default]
    container: monetdb/dev-builds:${{ matrix.branch }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup database
        run: |
          cd test 
          ./initfarm.sh
          ./initdb.sh
      -
        name: Run tests
        run: python3 setup.py test
